services:
  redis:
    ports: !override []

  postgres:
    environment: !override []
    env_file: './secrets/.env.docker.prod'
    ports: !override []
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: 'flashcard-server:latest'
    container_name: server
    restart: always
    volumes:
      - './secrets/.env:/app/.env'
      - './secrets/jamesryans-experiment-486190bd56d8.json:/app/jamesryans-experiment-486190bd56d8.json'
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
        restart: true
