name: Deploy Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: flashcard-server:latest
          context: "{{defaultContext}}:server"
          outputs: type=docker,dest=${{ runner.temp }}/flashcard-server.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flashcard-server-image
          path: ${{ runner.temp }}/flashcard-server.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: flashcard-server-image
          path: ${{ github.workspace }}/image/flashcard-server.tar

      - name: Deploy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "${{ github.workspace }}/image/flashcard-server.tar"
          target: /home/flashcard/
          strip_components: 6
          overwrite: true

      - name: Deploy compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "server/docker-compose.yml,server/docker-compose.prod.yml"
          target: /usr/src/flash-card/
          strip_components: 1
          overwrite: true

      - name: Load and re-create containers on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            docker load --input /home/flashcard/flashcard-server.tar
            docker compose --file=/usr/src/flash-card/docker-compose.yml --file=/usr/src/flash-card/docker-compose.prod.yml up --detach --force-recreate
